#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# A small delay to offset the startup of many applications to make launching them more reliable
$delay = 2

exec-once = caelestia-shell -d && caelestia-shell ipc call wallpaper set Pictures/Wallpapers/7046.jpg

exec-once = sleep $delay; touchpad-utils update # We must wait for Hyprland to finish initializing
exec-once = sleep $delay; mullvad-vpn # Starting too early seems to break notifications
exec-once = sleep $delay; handy

exec-once = [workspace special:scratchpad silent] sleep $delay; $terminal # Without the delay, caelesta overwrites the color scheme
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
