$primary_paletteKeyColor = aa6172
$secondary_paletteKeyColor = 8f6e74
$tertiary_paletteKeyColor = 967049
$neutral_paletteKeyColor = 817476
$neutral_variant_paletteKeyColor = 847375
$background = 191113
$onBackground = efdee0
$surface = 191113
$surfaceDim = 191113
$surfaceBright = 413738
$surfaceContainerLowest = 140c0e
$surfaceContainerLow = 22191b
$surfaceContainer = 261d1f
$surfaceContainerHigh = 312829
$surfaceContainerHighest = 3c3234
$onSurface = efdee0
$surfaceVariant = 524345
$onSurfaceVariant = d6c2c4
$inverseSurface = efdee0
$inverseOnSurface = 382e2f
$outline = 9f8c8f
$outlineVariant = 524345
$shadow = 000000
$scrim = 000000
$surfaceTint = ffb1c1
$primary = ffb1c1
$onPrimary = 551d2c
$primaryContainer = 713342
$onPrimaryContainer = ffd9df
$inversePrimary = 8d495a
$secondary = e4bdc3
$onSecondary = 43292f
$secondaryContainer = 5e4147
$onSecondaryContainer = ffd9df
$tertiary = ecbe91
$onTertiary = 462a09
$tertiaryContainer = b28960
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffd9df
$primaryFixedDim = ffb1c1
$onPrimaryFixed = 3a0718
$onPrimaryFixedVariant = 713342
$secondaryFixed = ffd9df
$secondaryFixedDim = e4bdc3
$onSecondaryFixed = 2b151a
$onSecondaryFixedVariant = 5b3f45
$tertiaryFixed = ffdcbd
$tertiaryFixedDim = ecbe91
$onTertiaryFixed = 2c1600
$onTertiaryFixedVariant = 60401d
$term0 = 353434
$term1 = ff4f79
$term2 = ffbbb2
$term3 = ffdedc
$term4 = b3a2d5
$term5 = ec8fa8
$term6 = ffba93
$term7 = efd1d0
$term8 = b49e9d
$term9 = ff8297
$term10 = ffd3cd
$term11 = fff1f0
$term12 = dcbc93
$term13 = fba8ba
$term14 = ffd1c0
$term15 = ffffff
$rosewater = ffedee
$flamingo = fdd9de
$pink = ffd1dd
$mauve = ffa5cc
$red = ff94ae
$maroon = f5aab9
$peach = ffbdc0
$yellow = ffedeb
$green = ffd8c5
$teal = ffdb94
$sky = ebd1ff
$sapphire = f2b2f2
$blue = f8a2d7
$lavender = ffb8dd
$klink = bc6ca5
$klinkSelection = bc6ca4
$kvisited = c85c8b
$kvisitedSelection = c85c89
$knegative = ea4f78
$knegativeSelection = ea5076
$kneutral = ff8691
$kneutralSelection = ff8690
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = efdee0
$subtext1 = d6c2c4
$subtext0 = 9f8c8f
$overlay2 = 8b7a7c
$overlay1 = 766769
$overlay0 = 645658
$surface2 = 524547
$surface1 = 403437
$surface0 = 2c2225
$base = 191113
$mantle = 191113
$crust = 181012
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
